# Generated by Django 4.0.1 on 2022-01-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='id',
            field=models.IntegerField(primary_key=b'I01\n', serialize=False),
        ),
        migrations.CreateModel(
            name='Monster_HZV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField()),
                ('part_name', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('sever', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('ammo', models.IntegerField()),
                ('fire', models.IntegerField()),
                ('water', models.IntegerField()),
                ('thunder', models.IntegerField()),
                ('ice', models.IntegerField()),
                ('dragon', models.IntegerField()),
                ('stun', models.IntegerField()),
                ('monster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster_api.monster')),
            ],
        ),
    ]
